"""Estrutura inicial do banco de dados

Revision ID: 01abccac9173
Revises: 
Create Date: 2025-10-12 19:38:03.039024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01abccac9173'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('chefe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chefe_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_completo', sa.String(length=150), nullable=False),
    sa.Column('nome_guerra', sa.String(length=50), nullable=False),
    sa.Column('identidade', sa.String(length=20), nullable=False),
    sa.Column('posto_grad', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('papel', sa.Enum('MILITAR', 'CHEFE_SECAO', 'GESTOR', name='papelusuario'), nullable=False),
    sa.Column('secao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['secao_id'], ['secao.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identidade'),
    sa.UniqueConstraint('nome_guerra')
    )
    op.create_table('periodo_aquisitivo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('ano_referencia', sa.Integer(), nullable=False),
    sa.Column('data_inicio_periodo', sa.Date(), nullable=False),
    sa.Column('data_fim_periodo', sa.Date(), nullable=False),
    sa.Column('dias_saldo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solicitacao_ferias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitante_id', sa.Integer(), nullable=False),
    sa.Column('periodo_aquisitivo_id', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('dias_solicitados', sa.Integer(), nullable=False),
    sa.Column('tipo_solicitacao', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('SOLICITADA', 'APROVADA_CHEFE', 'APROVADA_GESTOR', 'REPROVADA', 'ALTERADA', 'CANCELADA', name='statusferias'), nullable=False),
    sa.Column('data_solicitacao', sa.DateTime(), nullable=True),
    sa.Column('justificativa_reprovacao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['periodo_aquisitivo_id'], ['periodo_aquisitivo.id'], ),
    sa.ForeignKeyConstraint(['solicitante_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solicitacao_ferias')
    op.drop_table('periodo_aquisitivo')
    op.drop_table('usuario')
    op.drop_table('secao')
    # ### end Alembic commands ###
