"""empty message

Revision ID: 17b3f84f8ff7
Revises: 6b918fb98d15
Create Date: 2025-10-11 22:34:10.284728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17b3f84f8ff7'
down_revision = '6b918fb98d15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('periodo_aquisitivo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('ano_referencia', sa.Integer(), nullable=False),
    sa.Column('data_inicio_periodo', sa.Date(), nullable=False),
    sa.Column('data_fim_periodo', sa.Date(), nullable=False),
    sa.Column('dias_saldo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('periodo_aquisitivo')
    # ### end Alembic commands ###
