"""empty message

Revision ID: 5e582af7c909
Revises: 17b3f84f8ff7
Create Date: 2025-10-11 22:44:36.379074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e582af7c909'
down_revision = '17b3f84f8ff7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitacao_ferias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitante_id', sa.Integer(), nullable=False),
    sa.Column('periodo_aquisitivo_id', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('dias_solicitados', sa.Integer(), nullable=False),
    sa.Column('tipo_solicitacao', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('SOLICITADA', 'APROVADA_CHEFE', 'APROVADA_GESTOR', 'REPROVADA', 'ALTERADA', 'CANCELADA', name='statusferias'), nullable=False),
    sa.Column('data_solicitacao', sa.DateTime(), nullable=True),
    sa.Column('justificativa_reprovacao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['periodo_aquisitivo_id'], ['periodo_aquisitivo.id'], ),
    sa.ForeignKeyConstraint(['solicitante_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solicitacao_ferias')
    # ### end Alembic commands ###
