"""empty message

Revision ID: 6b918fb98d15
Revises: 
Create Date: 2025-10-11 22:24:03.036998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b918fb98d15'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('chefe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chefe_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_completo', sa.String(length=150), nullable=False),
    sa.Column('nome_guerra', sa.String(length=50), nullable=False),
    sa.Column('identidade', sa.String(length=20), nullable=False),
    sa.Column('posto_grad', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('papel', sa.Enum('MILITAR', 'CHEFE_SECAO', 'GESTOR', name='papelusuario'), nullable=False),
    sa.Column('secao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['secao_id'], ['secao.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identidade')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    op.drop_table('secao')
    # ### end Alembic commands ###
